name: Terraform CI/CD with Approval and AWS Secrets Manager

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  SECRET_NAME: my-demo-secret   # 👈 Your secret name in AWS Secrets Manager

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve Secret from AWS Secrets Manager
        id: get-secret
        run: |
          echo "Fetching secret from AWS Secrets Manager..."
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text)
          echo "secret_value=$SECRET_VALUE" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          TF_VAR_secret_json: ${{ steps.get-secret.outputs.secret_value }}
        run: terraform plan -out=tfplan

      - name: Upload plan file
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

  terraform-apply:
    name: Terraform Apply (with Approval)
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: production     # 👈 Requires manual approval before execution

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve Secret from AWS Secrets Manager
        id: get-secret
        run: |
          echo "Fetching secret from AWS Secrets Manager..."
          SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id $SECRET_NAME --query SecretString --output text)
          echo "secret_value=$SECRET_VALUE" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_VAR_secret_json: ${{ steps.get-secret.outputs.secret_value }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
